### ISSUE TITLE
Question - Targetting a specific poetry version

### ISSUE THREAD

**Issue by BigJerBD** [CircleCI-Public/cimg-python#114]
For some reasons, I have to use the pre-released poetry version (1.2.0a2) for a project. 

However when I do that I cannot use this circleci image for my tests since it seems to target  a 1.1.x versions which is not forward compatible with 1.2.x 

What are my options to be able to use this specific poetry version while using this image? Thanks :)

**Comment by JalexChen** [comment]
HI @BigJerBD,

Unfortunately at this time, we do not support any pre-release packages as we would like our Convenience images to function with stable releases in order to for users to reproduce results reliably. In this case, since it's not forward compatible, a couple of options exist:

- During the pipeline, manually install the version of poetry you'd like to use per the [docs](https://python-poetry.org/docs/)
`python get-poetry.py --version 0.12.0`
`POETRY_VERSION=0.12.0 python get-poetry.py`

- Depending on your use case, you can also choose to create your own image or utilize the Dockerfile.template and edit line 43 with the commands located on the [poetry docs](https://python-poetry.org/docs/master/#installing-with-the-official-installer)

**Comment by BigJerBD** [comment]
Thank you for the answer :) The forward compatibility issue comes from the poetry.lock  so I have decided to simply do a `poetry update` to replace it with a valid version. 

If I ran into other problems i'll probably do the second options. Thanks :)
