### ISSUE TITLE
Python 3.8 not installed when using cimg/python:3.8-node

### ISSUE THREAD

**Issue by mmshin** [CircleCI-Public/cimg-python#131]
I reran the job with SSH. 
running `pyenv` gives me 
```
/home/circleci/.pyenv/libexec/pyenv-help: line 157: exec: pyenv-commands: not found
```

**Comment by jrgarcia** [comment]
I'm using `cimg/python:3.7.7` and running into the same thing. `pip` and the correct `python` version are not available and I get

```shell
/home/circleci/.pyenv/libexec/pyenv-help: line 156: exec: pyenv-commands: not found
```
when running `pyenv` from SSH.

**Comment by JalexChen** [comment]
hey @mmshin and @jrgarcia - would you be able to give us a build and the commands you're using?

technically, you should not need to run the specific command `pyenv-commands` since the pyenv shim will redirect an equivalent command e.g `pyenv commands` to the libexec directory and run the modules there.

Could you please try this out and let us know if it works?

**Comment by felicianotech** [comment]
I've just run `3.8-node` and it gives me a Python v3.8.x version: https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/808/workflows/bcb367db-c688-4e6d-a791-14e96a536500/jobs/1820

I also ran a test build with `3.7.7` and that gave me the correct version as well: https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/809/workflows/41a3af3e-b17e-4d88-b338-27c2fdad70aa/jobs/1821

**Comment by JalexChen** [comment]
Closing this out as it was kinda of a duplicate. Please reopen if the issue continues to persist
