### ISSUE TITLE
Unable to execute pyenv-version-name

### ISSUE THREAD

**Issue by m0smith** [CircleCI-Public/cimg-python#133]
The pyenv functions like pyenv-version-name cannot be executed because /home/circleci/.pyenv/libexec is missing from the PATH

**Comment by JalexChen** [comment]
hey @m0smith, what's the use case and would using `pyenv version-name` as an alternative work?

**Comment by JalexChen** [comment]
hey @m0smith - what's the use case for this and are there any errors that are popping up? 

technically, you wouldn't need to use `pyenv-version-name` or any of the modules in the libexec directory since the pyenv shim works by redirecting commands. for example, `pyenv version-name` is the equivalent of `pyenv-version-name` in libexec

Let us know if this would work for you

**Comment by JalexChen** [comment]
Closing this out. Please reopen if you continue to run into an issue
