### ISSUE TITLE
Python v3.11.0 & python-attr

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-python#168]
There is a compatibility with this combo that is causing problems with some Python tools. For example, as of the time this issue is opened, `pipenv` on our `cimg/python:3.11.0` images is partially broken. This is an upstream issue among these projects. As fixes/updated dependencies roll out, we'll make a decision if we need to update anything on our end.

Some resources:

- https://github.com/python-attrs/attrs/issues/907
- https://github.com/pypa/pipenv/issues/5449

**Comment by JalexChen** [comment]
@felicianotech both of the upstream issues with attr and pipenv have been resolved. it looks like 3.11.0 is still the most used version by a good amount over the past 1-2 months. 

the fix for pipenv was merged 2 days after our 3.11.1 release, so both of these images would be affected.

it doesn't look like any issues have been raised though. i'm thinking until that happens we don't cut a new release for those two?
