### ISSUE TITLE
Python:3.11.1-node Pulls Old Node cimg

### ISSUE THREAD

**Issue by jmccraw** [CircleCI-Public/cimg-python#179]
The current LTS for Node is `18.13.0`, but `python:3.11.1-node` seems to still be pulling `18.12.1`.

https://github.com/CircleCI-Public/cimg-python/blob/3579d5c62e889a01005ffc21ce5f4a68732eacfe/3.11/node/Dockerfile#L8

https://raw.githubusercontent.com/CircleCI-Public/cimg-node/main/ALIASES returns:
```txt
lts=18.13.0
current=19.5.0
```
Old `18.12.1` images reflected here, as well, https://circleci.com/developer/images/image/cimg/python#image-name

**Comment by JalexChen** [comment]
@jmccraw - the python images were released [12/12](https://github.com/CircleCI-Public/cimg-python/pull/176), however, the latest node lts was released [2 weeks ago](https://github.com/CircleCI-Public/cimg-node/pull/313).

it makes sense that the python image is pulling in `18.12.1` since we are not creating new images because that was what the most current version of lts node was at the time.

if it's absolutely imperative to use node 18.13.0, there are a couple options: you could:
1) use the node orb to update the version of node
2) update manually in the configuration
3) run build_images.sh again locally + create a custom image and use that instead.
