### ISSUE TITLE
Support for 3.10 (and other future alpha/beta/rc releases of Python)

### ISSUE THREAD

**Issue by cjw296** [CircleCI-Public/cimg-python#91]
The old `circleci/python` images supported alphas, betas and RCs which was really helpful to get library supported before the final release and, indeed, to find bugs in Python before the final releases were made.

This appears not to have been done in the new `cimg` images. Please could we have that back?

Here's some example Issues/PRs where these would be helpful:

https://github.com/Simplistix/testfixtures/pull/158
https://github.com/cjw296/sybil/pull/27

**Comment by felicianotech** [comment]
Hi.

This is definitely something we are considering. We have a [CircleCI Idea](https://ideas.circleci.com/images/p/support-beta-and-rc-versions) that is tracking this user feature request. I'd recommend giving it an upvote to add your support to the request. We're tracking this there rather than here since it's something that will pertain to all of our images, not just Python.
